### ISSUE TITLE
home page design

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#3]
Design the home page! 

Log in to bbottoms.editllc.com/wp-admin and look at the theme we're using. 

Go here and learn about the theme features and some documentation on it: 
https://slocumthemes.com/wordpress-themes/modern-estate-theme/

Things to keep in mind for the home page:

- No image carousel for now, just a hero image
- Keep the search for his listings on the home page
- Feature his latest 3 or so listings
- Put his blog posts below that
- Social media links at both top and bottom

due:
10-25-15    6p

**Comment by rodneystrong** [comment]
FYI his current live site is:
buyorsellfresno.com

@jperez4509 already got all the content migrated over, but it wouldn't hurt to do a double-check yourself.

**Comment by rodneystrong** [comment]
Meg, this site takes priority over the other tasks you have. 
As always, if you're not able to make the due date on this, suggest a new one we can work with.

**Comment by vanderbeam** [comment]
I have a few questions about this one. I'm still getting familiar with the theme. It's much different than anything I've worked with in WordPress before.

I'm curious, because I'm coming it halfway through development and it's always questionable when using a WP theme, as to what the criteria for this front page design is. Does he want the same colour scheme as his current website? Did he choose this theme or did we and how much do you want me to tweak? Should I be going in and making all the edges sharp like on his current website or does he want something completely different? Do you just want me to start editing the theme's CSS until it looks the way I think it looks good? 
Don't to assume and assume wrong.

- Should I just remove the MLS page since the property search follows through the pages?
- There aren't any testimonials on the live site. He actually doesn't have any reviews at all (at least not on his top few google results). I found a classy looking review plugin here: https://wordpress.org/plugins/wp-customer-reviews/
Want me to go ahead and install that plugin and get it up and running on the testimonials page?
- For the contact page, on his live site he only has a single input box for people to type in their email and subscribes you to his mailing list. Do you want me to download a form plugin and set up a generic contact form or create a subscription thing like he has on his current site? Maybe both?

**Comment by rodneystrong** [comment]
With this one, I'll need you to make assumptions and take charge. Do as you did with the codergirlz site in terms of ownership. Crank out an initial draft and ping me for feedback. Don't be afraid to assume incorrectly. 

We chose this theme and you can tweak as much as you need; the important part of this theme is that it has a predefined 'post type' specifically for home listings. If you look at his live site, his home listings are blog posts (not good). 

- No, dont remove the MLS page. 
- Client doesn't have testimonials yet. Yes, get the plugin and put it on the testimonials page (but this is NOT a priority. Priority is getting the home page design up and running)
- For the contact page, yes, do both. 

Some design inspiration: 
http://www.elegantthemes.com/demo/?theme=ElegantEstate

http://wpestatetheme.org/

**Comment by vanderbeam** [comment]
@rodneystrong I'm still working out some of the details but you can see the idea I'm heading with this: http://bbottoms.editllc.com/
Let me know what you think.

**Comment by rodneystrong** [comment]
not bad at all. keep goin. remember, there's no need to make it look like the old site.

**Comment by vanderbeam** [comment]
Well besides the footer and using the same hero image, how do you mean it looking like the old site?

**Comment by vanderbeam** [comment]
This theme has some of the most bizarre logic I've ever seen. Everything is intertwined with everything else and for some reasons resizing buttons effects the hero. @_@

**Comment by rodneystrong** [comment]
that's kinda what i meant. the header and footer still somewhat look like the old site, that's all. 

could you detail for me what exactly is holding you up here? I know there are several things but could you explain in step-by-step fashion one of those things so I can help troubleshoot?

**Comment by vanderbeam** [comment]
OK I'll jump right onto the footer and header. I'll see if I can vary it a bit. The hero picture is what was there when I took over the project. Should I jump onto the depositphotos and find a different one?

And I guess the instructions for this were just a little vague. I feel a little limited redesigning the wordpress theme but I was trying to make it look a little more "hip" with the pea green accent colour. 

I really liked the half page style on http://wpestatetheme.org/ but the way this theme works wouldn't really allow that styling. It was what I had initially tried though. 

I'm a little hesitant about installing the plugins I need for the rest of the content because you said that wasn't a priority. But I know I'm going to have to redesign the style in some of those plugins. 

Aside from redesigning the footer I guess I just need some critiques on the rest of the design?

**Comment by rodneystrong** [comment]
sorry i dont understand, i thought there was something specific about this theme that was holdin you back that you needed a second set of eyes on? 

should we just use a completely different theme and try to replicate the search and property listing functionality?

**Comment by vanderbeam** [comment]
Well there are some restrictions. Like only the "pro" version allows you to include widgets on the pages. So I have the choice of having the Property Search widget on ALL of the pages or only on the front page. But issues like that are kind of a WordPress thing, switching themes won't necessarily help with that. 

There are definitely things about this theme that I'm having issues with because everything is so intertwined, but that just means doing more work. Like there are about five different things that are effected by making changes to the post navigation (the issues I made a task for). So I'll have to go through the site and redesign those features by their IDs. That's not a big deal to me though, just a little bit of extra work. 

I just need feedback really. Let me know how you like the new footer and I still need the questions in my previous comment answered. 

http://bbottoms.editllc.com/

**Comment by rodneystrong** [comment]
ooooh nice nice nice meg  footer's much better.
